export type TourAction = 'citizen-login' | 'sample-chat' | 'prepare-plan' | 'admin-login';
export interface TourStep {
  id: string;
  chapter: 'Start' | 'Citizen' | 'Opportunities' | 'Admin';
  path: string;
  target: string;
  title: [string, string];
  body: [string, string];
  cue: [string, string];
  action?: TourAction;
}

// English, Bangla. Every step opens a real screen; only the example chat is local.
export const TOUR_STEPS: readonly TourStep[] = [
  { id: 'welcome', chapter: 'Start', path: '/', target: '.portal-hero-content', title: ['Welcome to Nagorik Shathi', 'নাগরিক সাথী পরিচিতি'], body: ['A guided walkthrough of the complete citizen journey and administration tools. Demo sign-in switches this browser to the seeded sample accounts; no registration or OTP is needed.', 'নাগরিকের সম্পূর্ণ যাত্রা ও প্রশাসনিক টুলের গাইড। ডেমো লগইন এই ব্রাউজারে নমুনা অ্যাকাউন্ট ব্যবহার করবে; নিবন্ধন বা OTP লাগবে না।'], cue: ['Present: “One assistant connects a citizen’s life situation to their next step.”', 'বলুন: “একজন সহকারী নাগরিকের পরিস্থিতি থেকে পরবর্তী পদক্ষেপ খুঁজে দেয়।”'] },
  { id: 'life-events', chapter: 'Start', path: '/', target: '#life-events', title: ['Start with a life event', 'জীবনের ঘটনা থেকে শুরু'], body: ['Citizens choose what happened to them, rather than having to know a ministry or programme name. Each choice opens matching programmes.', 'নাগরিক মন্ত্রণালয় বা কর্মসূচির নাম না জেনেও নিজের জীবনের ঘটনা বেছে নিতে পারেন। প্রতিটি ঘটনা সংশ্লিষ্ট কর্মসূচি খুলে দেয়।'], cue: ['Example: a lost job, medical treatment, or a child’s education.', 'উদাহরণ: চাকরি হারানো, চিকিৎসা বা সন্তানের পড়াশোনা।'] },
  { id: 'categories', chapter: 'Start', path: '/', target: '.portal-categories', title: ['Explore support categories', 'সহায়তার বিভাগ দেখুন'], body: ['Education, healthcare, allowances, agriculture, employment and other categories provide another route into the same programme catalogue.', 'শিক্ষা, স্বাস্থ্য, ভাতা, কৃষি, কর্মসংস্থানসহ বিভিন্ন বিভাগ থেকে একই কর্মসূচির তালিকা দেখা যায়।'], cue: ['The counts come from the programme catalogue.', 'সংখ্যাগুলো কর্মসূচির তালিকা থেকে আসে।'] },
  { id: 'process', chapter: 'Start', path: '/', target: '#how-it-works', title: ['The four-step journey', 'চার ধাপে নাগরিকের যাত্রা'], body: ['Tell your story → check eligibility → discover opportunities → follow an action plan. The rules decide eligibility; AI explains the result.', 'নিজের কথা বলুন → যোগ্যতা যাচাই → সুযোগ খুঁজুন → কর্মপরিকল্পনা অনুসরণ করুন। নিয়ম যোগ্যতা নির্ধারণ করে; AI ফলাফল ব্যাখ্যা করে।'], cue: ['This is the central story for your presentation.', 'প্রেজেন্টেশনের মূল গল্প এটিই।'] },
  { id: 'support', chapter: 'Start', path: '/', target: '#citizen-support', title: ['Trust and common questions', 'আস্থা ও সাধারণ প্রশ্ন'], body: ['The FAQ explains privacy, cost, applications and how to handle incorrect information. Recommendations keep their evidence and verification labels.', 'FAQ-তে গোপনীয়তা, খরচ, আবেদন ও ভুল তথ্যের করণীয় আছে। সুপারিশে প্রমাণ ও যাচাইয়ের পরিচিতি থাকে।'], cue: ['Citizens can inspect the basis of a recommendation.', 'নাগরিক সুপারিশের ভিত্তি দেখতে পারেন।'] },
  { id: 'registration', chapter: 'Start', path: '/register', target: 'main', title: ['Registration and recovery', 'নিবন্ধন ও অ্যাকাউন্ট পুনরুদ্ধার'], body: ['Normal users register with a mobile number, verify a code and choose a PIN. Forgotten PIN recovery is available from sign-in. This tour does not submit registration or reset credentials.', 'সাধারণ ব্যবহারকারী মোবাইল নম্বর, কোড যাচাই ও PIN দিয়ে নিবন্ধন করেন। লগইন থেকে PIN পুনরুদ্ধার করা যায়। ট্যুরে নিবন্ধন বা PIN পরিবর্তন করা হবে না।'], cue: ['Next opens the sign-in demonstration.', 'পরের ধাপে লগইনের ডেমো দেখুন।'] },
  { id: 'login', chapter: 'Start', path: '/login', target: 'main', title: ['Simulated citizen sign-in', 'নাগরিকের ডেমো লগইন'], body: ['Continue signs in as Rahima, the seeded citizen example, using the existing demo credentials. You do not need to type a phone number, PIN or OTP.', 'চালিয়ে গেলে বিদ্যমান ডেমো তথ্য দিয়ে নমুনা নাগরিক রহিমার অ্যাকাউন্টে লগইন হবে। নম্বর, PIN বা OTP লিখতে হবে না।'], cue: ['Rahima is a sample citizen from Rangpur seeking support after widowhood.', 'রহিমা রংপুরের একজন নমুনা নাগরিক; স্বামী হারানোর পর সহায়তা খুঁজছেন।'], action: 'citizen-login' },
  { id: 'dashboard', chapter: 'Citizen', path: '/dashboard', target: '.portal-dashboard-welcome', title: ['Your citizen workspace', 'নাগরিকের ড্যাশবোর্ড'], body: ['The dashboard brings personalized opportunities, urgent tasks, saved programmes and recent conversations together.', 'ড্যাশবোর্ডে ব্যক্তিগত সুপারিশ, জরুরি কাজ, সেভ করা কর্মসূচি ও সাম্প্রতিক কথোপকথন একসঙ্গে থাকে।'], cue: ['A citizen can immediately see what to do next.', 'নাগরিক সঙ্গে সঙ্গেই পরবর্তী করণীয় দেখতে পারেন।'] },
  { id: 'recommendations', chapter: 'Citizen', path: '/dashboard', target: '.portal-opportunity-grid', title: ['Recommendations with reasons', 'কারণসহ সুপারিশ'], body: ['Each card shows eligibility, a reason, benefits, deadline and verification status. Open a card to inspect every eligibility condition.', 'প্রতিটি কার্ডে যোগ্যতা, কারণ, সুবিধা, সময়সীমা ও যাচাইয়ের অবস্থা থাকে। বিস্তারিত খুলে প্রতিটি শর্ত দেখা যায়।'], cue: ['Highlight “Why you qualify,” rather than just the eligibility badge.', 'শুধু যোগ্যতার ব্যাজ নয়, “কেন আপনি যোগ্য” অংশ দেখান।'] },
  { id: 'profile', chapter: 'Citizen', path: '/profile', target: 'main', title: ['Profile and eligibility inputs', 'প্রোফাইল ও যোগ্যতার তথ্য'], body: ['District, household, occupation, income and life events help the rule engine make a better assessment. Missing details lead to questions, not guesses.', 'জেলা, পরিবার, পেশা, আয় ও জীবনের ঘটনা দিয়ে নিয়ম আরও নির্ভুলভাবে যাচাই হয়। তথ্য না থাকলে প্রশ্ন করা হয়, অনুমান নয়।'], cue: ['No profile changes are submitted by the tour.', 'ট্যুর নিজে প্রোফাইল পরিবর্তন সাবমিট করে না।'] },
  { id: 'assistant', chapter: 'Citizen', path: '/chat', target: '.portal-chat', title: ['Ask in natural language', 'নিজের ভাষায় প্রশ্ন করুন'], body: ['Citizens can type Bangla or English, use suggestion prompts, and speak when voice input is available. Conversation history is also accessible.', 'নাগরিক বাংলা বা ইংরেজিতে লিখতে, প্রস্তাবিত প্রশ্ন বেছে নিতে ও ভয়েস থাকলে কথা বলতে পারেন। আগের কথাও দেখা যায়।'], cue: ['We will demonstrate a local example without calling a live AI provider.', 'লাইভ AI-কে কল না করেই একটি স্থানীয় উদাহরণ দেখাব।'] },
  { id: 'sample-question', chapter: 'Citizen', path: '/chat', target: '.portal-chat-composer', title: ['Run the example conversation', 'উদাহরণ কথোপকথন চালান'], body: ['Our example: “My husband has died; what support can I get?” Continue displays a clearly labeled simulated answer and a programme card. It does not create a conversation or update the profile.', 'উদাহরণ: “আমার স্বামী মারা গেছেন; আমি কী সহায়তা পাব?” চালিয়ে গেলে স্পষ্টভাবে চিহ্নিত ডেমো উত্তর ও কর্মসূচির কার্ড দেখাবে। কথোপকথন সংরক্ষণ বা প্রোফাইল পরিবর্তন হবে না।'], cue: ['Reliable for a timed presentation, even without an AI key.', 'AI key ছাড়াও সময়বদ্ধ প্রেজেন্টেশনে দেখানো যায়।'], action: 'sample-chat' },
  { id: 'sample-answer', chapter: 'Citizen', path: '/chat', target: '[data-tour="chat-log"]', title: ['Explain, then show the next step', 'ব্যাখ্যা ও পরবর্তী পদক্ষেপ'], body: ['The demo answer shows an opportunity with an explanation. In normal conversations the assistant uses the citizen’s profile and retrieved evidence; the tour example is illustrative.', 'ডেমো উত্তরে ব্যাখ্যাসহ একটি সুযোগ আছে। স্বাভাবিক কথোপকথনে প্রোফাইল ও সংগৃহীত প্রমাণ ব্যবহার হয়; ট্যুরের উত্তর শুধু উদাহরণ।'], cue: ['Open “Sources” to show where the example’s programme information comes from.', 'তথ্যের উৎস দেখাতে “উৎস” খুলতে পারেন।'] },
  { id: 'voice', chapter: 'Citizen', path: '/chat', target: '[data-tour="voice-launch"]', title: ['Voice and reading assistance', 'ভয়েস ও পড়ে শোনানো'], body: ['The microphone supports speaking, navigation commands and help. Responses can be read aloud. Browser permissions are requested only when someone chooses to use voice.', 'মাইক দিয়ে কথা বলা, নেভিগেশন ও সাহায্য পাওয়া যায়। উত্তর পড়ে শোনানোও যায়। ব্যবহারকারী ভয়েস বেছে নিলেই ব্রাউজারের অনুমতি চাওয়া হয়।'], cue: ['The tour does not request microphone permission.', 'ট্যুর মাইক্রোফোনের অনুমতি চায় না।'] },
  { id: 'browse', chapter: 'Opportunities', path: '/opportunities', target: '.portal-opportunity-browser', title: ['Search, filter and sort', 'খুঁজুন, ফিল্টার ও সাজান'], body: ['Search by programme, filter categories or eligibility, and sort by relevance, deadline, newest or amount. Filters are reflected in the URL.', 'কর্মসূচি খুঁজুন, বিভাগ বা যোগ্যতা দিয়ে ফিল্টার করুন এবং প্রাসঙ্গিকতা, সময়সীমা, নতুন বা অর্থ অনুযায়ী সাজান। ফিল্টার URL-এ থাকে।'], cue: ['You can pause the tour to try filters yourself.', 'নিজে ফিল্টার দেখতে ট্যুর বিরতি দিতে পারেন।'] },
  { id: 'detail', chapter: 'Opportunities', path: '/opportunities/widow-allowance', target: '.portal-programme-detail > header', title: ['Programme overview', 'কর্মসূচির বিস্তারিত'], body: ['The programme page brings benefits, eligibility, documents, application process, sources and related support into one screen.', 'এক স্ক্রিনে সুবিধা, যোগ্যতা, প্রয়োজনীয় কাগজ, আবেদনপ্রক্রিয়া, উৎস ও সংশ্লিষ্ট সহায়তা থাকে।'], cue: ['Our example is the Widow Allowance sample programme.', 'উদাহরণ হিসেবে বিধবা ভাতার নমুনা কর্মসূচি দেখাচ্ছি।'] },
  { id: 'eligibility', chapter: 'Opportunities', path: '/opportunities/widow-allowance', target: '[data-tour="eligibility"]', title: ['Condition-by-condition eligibility', 'প্রতিটি শর্ত ধরে যোগ্যতা'], body: ['Every condition shows the programme requirement, what the citizen supplied, and whether it is met, unmet or unknown. This is the deterministic eligibility trace.', 'প্রতিটি শর্তে কর্মসূচির প্রয়োজন, নাগরিকের তথ্য এবং পূরণ হয়েছে কি না বা অজানা তা দেখা যায়। এটিই নিয়মভিত্তিক যোগ্যতার ব্যাখ্যা।'], cue: ['Present: “The AI cannot invent an eligibility decision.”', 'বলুন: “AI নিজে যোগ্যতার সিদ্ধান্ত বানাতে পারে না।”'] },
  { id: 'documents', chapter: 'Opportunities', path: '/opportunities/widow-allowance', target: '[data-tour="documents"]', title: ['Documents and application process', 'কাগজপত্র ও আবেদনপ্রক্রিয়া'], body: ['Citizens see which documents to collect and the steps required to apply. These steps also provide the basis for an action plan.', 'নাগরিক কী কী কাগজ সংগ্রহ করবেন ও কীভাবে আবেদন করবেন তা দেখেন। এই ধাপ থেকেই কর্মপরিকল্পনা হয়।'], cue: ['Information becomes practical preparation.', 'তথ্য থেকে বাস্তব প্রস্তুতি তৈরি হয়।'] },
  { id: 'evidence', chapter: 'Opportunities', path: '/opportunities/widow-allowance', target: '[data-tour="sources"]', title: ['Evidence and confidence', 'প্রমাণ ও আস্থার মাত্রা'], body: ['Source documents and confidence explanations make the recommendation inspectable. Unverified sample records keep their honest verification labels.', 'উৎসের নথি ও আস্থার ব্যাখ্যা দিয়ে সুপারিশ যাচাই করা যায়। যাচাই না করা নমুনা তথ্যে সেটি স্পষ্টভাবে চিহ্নিত থাকে।'], cue: ['Next saves this programme and prepares its plan in Rahima’s demo account.', 'পরের ধাপে রহিমার ডেমো অ্যাকাউন্টে কর্মসূচি সেভ ও পরিকল্পনা তৈরি হবে।'], action: 'prepare-plan' },
  { id: 'saved', chapter: 'Opportunities', path: '/saved', target: '.portal-saved-board', title: ['Saved programmes and application status', 'সেভ করা কর্মসূচি ও আবেদনের অবস্থা'], body: ['Saved support stays on the tracker. Citizens can add notes and move through preparation, application and outcome statuses.', 'সেভ করা সহায়তা ট্র্যাকারে থাকে। নোট যোগ করা এবং প্রস্তুতি, আবেদন ও ফলাফলের অবস্থা বদলানো যায়।'], cue: ['The tour prepares only the seeded demo account’s example programme.', 'ট্যুর শুধু নমুনা অ্যাকাউন্টের উদাহরণ কর্মসূচি প্রস্তুত করে।'] },
  { id: 'plan', chapter: 'Opportunities', path: '/saved', target: '[data-tour="action-plans"]', title: ['Turn a recommendation into tasks', 'সুপারিশ থেকে কাজের তালিকা'], body: ['The generated plan groups tasks, document preparation and deadlines. Completing a task updates progress; the tour leaves tasks untouched.', 'পরিকল্পনায় কাজ, কাগজ প্রস্তুতি ও সময়সীমা থাকে। কাজ শেষ করলে অগ্রগতি বদলায়; ট্যুর কাজের অবস্থা বদলাবে না।'], cue: ['This is the “what should I do next?” moment.', 'এখানেই “এখন কী করব?” প্রশ্নের উত্তর।'] },
  { id: 'timeline', chapter: 'Opportunities', path: '/timeline', target: 'main', title: ['Deadlines and timeline', 'সময়সীমা ও সময়সূচি'], body: ['The timeline organizes upcoming programme deadlines and plan tasks. Citizens can inspect upcoming work and completion.', 'সময়সূচিতে কর্মসূচির সময়সীমা ও পরিকল্পনার কাজ দেখা যায়। নাগরিক আসন্ন কাজ ও অগ্রগতি দেখতে পারেন।'], cue: ['Connect this screen back to the action plan.', 'কর্মপরিকল্পনার সঙ্গে এই স্ক্রিনের সম্পর্ক দেখান।'] },
  { id: 'nearby', chapter: 'Opportunities', path: '/nearby', target: '.portal-nearby', title: ['Where to get help', 'কোথায় সহায়তা পাওয়া যায়'], body: ['Nearby offices can be browsed by district and service. Distance-based results are available when a user chooses location access.', 'জেলা ও সেবা ধরে কাছের অফিস দেখা যায়। ব্যবহারকারী অবস্থানের অনুমতি দিলে দূরত্ব অনুযায়ী ফল দেখা যায়।'], cue: ['The tour does not request location permission.', 'ট্যুর অবস্থানের অনুমতি চায় না।'] },
  { id: 'notifications', chapter: 'Opportunities', path: '/notifications', target: 'main', title: ['Notifications and reminders', 'নোটিফিকেশন ও মনে করানো'], body: ['Citizens can review notifications and reminders here. Push notification preferences are managed in Settings.', 'নাগরিক এখানে নোটিফিকেশন ও মনে করানো দেখতে পারেন। পুশ নোটিফিকেশন সেটিংস থেকে নিয়ন্ত্রণ করা হয়।'], cue: ['No notifications are sent by the tour.', 'ট্যুর কোনো নোটিফিকেশন পাঠায় না।'] },
  { id: 'settings', chapter: 'Opportunities', path: '/settings', target: 'main', title: ['Language and accessibility', 'ভাষা ও সহজে ব্যবহার'], body: ['Settings include light, dark and sunlight themes, text size, numeral preferences, reduced motion, voice and notification controls. Bangla and English are supported throughout.', 'সেটিংসে লাইট, ডার্ক ও রোদে দেখার থিম, লেখার আকার, সংখ্যা, কম অ্যানিমেশন, ভয়েস ও নোটিফিকেশন আছে। পুরো অ্যাপে বাংলা ও ইংরেজি আছে।'], cue: ['Next switches to the seeded administrator demo account.', 'পরের ধাপে নমুনা প্রশাসকের অ্যাকাউন্টে যাবে।'], action: 'admin-login' },
  ...[
    ['admin', '/admin', 'Administration overview', 'প্রশাসনিক ড্যাশবোর্ড', 'Staff manage the knowledge base, verification work and background jobs.', 'কর্মীরা তথ্যভান্ডার, যাচাই ও ব্যাকগ্রাউন্ড কাজ পরিচালনা করেন।'],
    ['admin-programmes', '/admin/programmes', 'Programme management', 'কর্মসূচি পরিচালনা', 'Staff inspect programme records and verification status. The tour does not verify or edit records.', 'কর্মীরা কর্মসূচি ও যাচাইয়ের অবস্থা দেখেন। ট্যুর তথ্য সম্পাদনা বা যাচাই করবে না।'],
    ['admin-organisations', '/admin/organisations', 'Organizations', 'প্রতিষ্ঠান', 'Organizations connect programmes with their providers and provenance.', 'প্রতিষ্ঠানের সঙ্গে কর্মসূচি, সেবাদাতা ও তথ্যের উৎস যুক্ত থাকে।'],
    ['admin-rules', '/admin/rules', 'Eligibility rule management', 'যোগ্যতার নিয়ম পরিচালনা', 'Versioned rules keep eligibility decisions traceable and maintainable.', 'সংস্করণভিত্তিক নিয়ম দিয়ে যোগ্যতার সিদ্ধান্ত অনুসরণ ও পরিচালনা করা যায়।'],
    ['admin-moderation', '/admin/moderation', 'Moderation and review', 'পর্যালোচনা ও মডারেশন', 'Review queues help staff handle reported information and feedback.', 'রিভিউ তালিকায় কর্মীরা রিপোর্ট করা তথ্য ও মতামত দেখেন।'],
    ['admin-ai-logs', '/admin/ai-logs', 'AI logs and diagnostics', 'AI লগ ও ডায়াগনস্টিক', 'Staff can inspect AI activity and failures to understand how the assistant behaves.', 'AI কীভাবে কাজ করছে তা বুঝতে কর্মীরা কার্যক্রম ও ব্যর্থতার লগ দেখেন।'],
    ['admin-users', '/admin/users', 'Users and roles', 'ব্যবহারকারী ও ভূমিকা', 'Role-based access separates citizen, moderator and administrator permissions. No roles are changed by the tour.', 'ভূমিকাভিত্তিক অনুমতিতে নাগরিক, মডারেটর ও প্রশাসকের কাজ আলাদা থাকে। ট্যুর কোনো ভূমিকা বদলায় না।'],
  ].map(([id, path, en, bn, enBody, bnBody]) => ({ id: id!, chapter: 'Admin' as const, path: path!, target: 'main', title: [en!, bn!] as [string, string], body: [enBody!, bnBody!] as [string, string], cue: ['Administration is a read-only walkthrough.', 'প্রশাসনিক অংশে শুধু দেখানো হয়।'] as [string, string] })),
  { id: 'finish', chapter: 'Admin', path: '/admin', target: 'main', title: ['You have completed the app tour', 'অ্যাপ ট্যুর সম্পূর্ণ হয়েছে'], body: ['You have seen the complete journey: life event → recommendation → eligibility → plan → deadline → office, plus administration. Finish signs out the demo account and returns to the home page.', 'জীবনের ঘটনা → সুপারিশ → যোগ্যতা → পরিকল্পনা → সময়সীমা → অফিস এবং প্রশাসনিক অংশ দেখেছেন। শেষ করলে ডেমো অ্যাকাউন্ট থেকে লগআউট হয়ে হোমে ফিরবেন।'], cue: ['Restart any time for your next presentation.', 'পরের প্রেজেন্টেশনে যেকোনো সময় আবার শুরু করুন।'] },
];
